version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "Ilyas1409" -Value "Ilyas1409"
            Set-Variable -Name "NGROK" -Value "1iN6VOq6BbE0hZqKi83tnAmfpDJ_56vkka4fHHQ7UFvkFRHoZ"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1
